### ISSUE TITLE
Addnodes

### ISSUE THREAD

**Issue by le2Ks** [NLC1609/caffeecoin#1]
Hi, any addnodes? Thx

**Comment by NLC1609** [comment]
Hi, I actually have a few nodes now, I have one in London and one in the United states(main nodes), they are both virtual machines, I also have one in Singapore(as a normal full node). You can also participate by going to the website https://caffeecoin.com/running_node.html and that will tell you all the ways you can run a node. You can also join the caffeecoin forum https://www.reddit.com/r/CaffeeCoin/  I will also be adding more nodes soon.

**Comment by le2Ks** [comment]
Hi, ok thank you for infos. Do you also have a discord group by any chance? thx

**Comment by NLC1609** [comment]
CaffeeCoin's websote = https://caffeecoin.com
Reddit = https://www.reddit.com/r/CaffeeCoin/
Discord General = https://discord.gg/MqZUNGmjU3
Discord R&D = https://discord.gg/YxjDxNSbum 
rocket.chat = coming soon

**Comment by NLC1609** [comment]
These are the resources that are currently available. Gonna be making more Lol

**Comment by le2Ks** [comment]
Awesome thx!
